---
- name:  slurp  sysctl 
  hosts: cgroup
  tasks:
    - name:  fetch a sysctl file 
      slurp:
        src: /etc/sysctl.conf
      register: k_content 
      ignore_errors: true

    - name: Decode r key 
      set_fact:
        r_content: "{{k_content.content | b64decode }}"

    - debug: 
        var: r_content

    - name: copy to the target 
      copy: 
        content: "{{r_content}}"
        dest: /home/vpcuser/configRepo/sysctl/sysctl-{{ ansible_hostname }}
      when: not r_content.failed
      delegate_to: jumphost-0
      remote_user: vpcuser




